getUpdates addition
jaebradley/tinder-client pull request #13
Opened 2018-05-15 14:30 UTC by Annihil

2018-05-15 14:40 UTC, Annihil commented
No idea why checks have failed :|

2018-05-16 13:00 UTC, jaebradley commented on src/index.js
> +    return this.client({
`eslint` violations

![image](https://user-images.githubusercontent.com/8136030/40118291-84b7b49e-58e7-11e8-9678-eabd7c3b6cf8.png)

2018-05-16 13:00 UTC, jaebradley requested changes
Looks good, just some linting errors

2018-05-16 15:45 UTC, Annihil commented
There are some errors unrelated with my changes now
`(Request failed with status code 400)`

2018-05-16 18:57 UTC, jaebradley commented on src/index.js
> +  getUpdates(timestamp) {
Do you think `from` might be a better name than `timestamp`? Also, should it have a default value of `''` - this will get all values since account creation, I think.

2018-05-16 19:55 UTC, jaebradley commented
@Annihil the `400`s are occurring because I have integration tests. These integration tests use environment variables that are set in my Travis configuration for this repository.

Per [the Travis documentation](https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions)

> Travis CI makes encrypted variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.

If you add the required environment variables to your Travis build for your fork that could cause the build to succeed.

2019-02-24 01:30 UTC, closed without merging

2019-02-24 01:36 UTC, jaebradley commented
:tada: This issue has been resolved in version 3.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/tinder-client)
- [GitHub release](https://github.com/jaebradley/tinder-client/releases/tag/v3.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: